package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
	"neo4j-version/graph/model"

	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

// Movie is the resolver for the movie field.
func (r *queryResolver) Movie(ctx context.Context, uuid string) (*model.Movie, error) {
	session := r.Driver.NewSession(neo4j.SessionConfig{})
	session.BeginTransaction()
	panic(fmt.Errorf("not implemented: Movie - movie"))
}

// Movies is the resolver for the movies field.
func (r *queryResolver) Movies(ctx context.Context, title *string, actor *string) ([]*model.Movie, error) {
	fmt.Println("check Movies query resolver")
	session := r.Driver.NewSession(neo4j.SessionConfig{})
	session.ReadTransaction()
	return nil, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
